In [0]:
import numpy as np

In [0]:
#Ejercicio 1: Muestra la versión de NumPy utilizada
print(np.version.version)

1.16.2


In [8]:
#Ejercicio 2: Crear un arreglo 1D con enteros positivos aleatorios
import random
yep=np.array([np.random.randint(1,30) for i in range(12)])
print(yep)

[ 9  1 29 22 22 22  1 18  5 28  7  5]


In [0]:
#Ejercicio 3: Crear un arreglo boleano

[(2*n+1)%2==0 for n in range(1,6)]

[False, False, False, False, False]

In [9]:
yep==20

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [11]:
np.array([True, False])

array([ True, False])

In [0]:
#Ejercicio 4: Extraer los items que sean divisibles en 3.
[element for element in yep if element % 3==0]

[21, 9, 27, 9, 27, 18, 27]

In [19]:
# yep 2 contiene un arreglo booleano 
yep2=yep%3==0
print(yep2)
print(yep)
print(yep[yep2])

[ True False False False False False False  True False False False False]
[ 9  1 29 22 22 22  1 18  5 28  7  5]
[ 9 18]


In [0]:
#Ejercicio 5:  Convierte el arreglo boleano de 1D a 2D 
#con tres filas (reshape)

arreglo=np.array(yep).reshape(3,4)
print(arreglo)

[[25  7 20 11]
 [25 24  8  1]
 [ 2 28 22  3]]


In [21]:
#Ejercicio 6: Obtén los items comunes entre dos arreglos

arr1=np.array(range(1,12))
arr2=np.array([z for z in range(1,12,2)])
interseccion=[j for j in arr1 if j in arr2]
print(arr1)
print(arr2)
print()
print(interseccion)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  3  5  7  9 11]

[1, 3, 5, 7, 9, 11]


In [23]:
print(np.intersect1d(arr1,arr2))


[ 1  3  5  7  9 11]


In [0]:
#Ejercicio 7. Extrae los números de un vector.
for element in interseccion:
    print(element)

1
3
5
7
9
11


In [0]:
#Ejercicio 8. Muestra solo 3 decimales en un vector.
[np.around(x,3) for x in np.sqrt(interseccion)]

[1.0, 1.732, 2.236, 2.646, 3.0, 3.317]

In [0]:
#Ejercicio 9. Crea una matriz de 3x3 con los valores del 0 a 8
matrix=np.arange(0,9).reshape(3,3)

In [0]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
#Ejercicio 10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices 
#donde los elementos sean diferente a cero.

test=[1,2,0,0,4,]
indices=[]
for pareja in list(enumerate(test)):
    if pareja[1]!=0:
        indices.append(pareja[0])
print(indices)


[0, 1, 4]


In [0]:
#Ejercicio 11.Crea un vector aleatorio de 30 elementos y 
#encuentra la media.

np.mean([np.random.randint(1,12) for i in range(0,30)])

5.766666666666667

In [0]:
#Ejercicio 12. Crea un arreglo 2D con 1 en los bordes y 0 
#dentro. Por ejemplo: 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 1

pool=[0,1]*10
[(x+1)%2 for x in pool]

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [0]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

In [0]:
#Crea una matriz de 5x5 
#con valores 1, 2, 3, 4 justo después de la diagonal.

claro=np.eye(5)
print(claro)
print()
claro2=claro
i=1
while i<=4:
        claro2[i][i-1]=i
        i+=1
print(claro2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [0]:
#Ejercicio 15. Normaliza una matriz aleatoria de 5x5

matriz=np.array([np.random.randint(2,6) for i in range(25)]).reshape(5,5)
normalizacion=matriz/np.linalg.det(matriz)
print(matriz)
print()
print(normalizacion)

[[3 3 5 3 3]
 [5 2 3 2 2]
 [5 5 3 4 2]
 [4 5 5 2 3]
 [3 5 5 3 5]]

[[-0.01304348 -0.01304348 -0.02173913 -0.01304348 -0.01304348]
 [-0.02173913 -0.00869565 -0.01304348 -0.00869565 -0.00869565]
 [-0.02173913 -0.02173913 -0.01304348 -0.0173913  -0.00869565]
 [-0.0173913  -0.02173913 -0.02173913 -0.00869565 -0.01304348]
 [-0.01304348 -0.02173913 -0.02173913 -0.01304348 -0.02173913]]
